parameters:
  hello_world: "Hello world!"

services:
  prestashop.link_block.repository:
    class: PrestaShop\LinkList\Repository\LinkBlockRepository
    arguments: ['@doctrine.dbal.default_connection', '%database_prefix%']

  # Grid data query builder
  prestashop.link_block.grid.query_builder:
    class: PrestaShop\LinkList\Core\Grid\Query\LinkBlockQueryBuilder
    arguments: ['@doctrine.dbal.default_connection', '%database_prefix%']

  # Grid Data Factory
  prestashop.link_block.grid.data_factory:
    class: PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory
    arguments:
    - '@prestashop.link_block.grid.query_builder'
    - '@prestashop.core.hook.dispatcher'

  # Link block grid Factory
  prestashop.link_block.grid.factory:
    autowire: true
    class: PrestaShop\LinkList\Core\Grid\LinkBlockGridFactory
    arguments:
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
      $dataFactory: '@prestashop.link_block.grid.data_factory'
      $filterFormFactory: '@prestashop.core.grid.filter.form_factory'

  # Link block form data provider
  prestashop.link_block.form_provider:
    class: PrestaShop\LinkList\Form\LinkBlockFormDataProvider

  prestashop.link_block.form_type:
    class: PrestaShop\LinkList\Form\Type\LinkBlockType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  # Link block form handler
  prestashop.link_block.form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\FormHandler'
    arguments:
    - '@=service("form.factory").createBuilder()'
    - '@prestashop.core.hook.dispatcher'
    - '@prestashop.link_block.form_provider'
    -
      'link_block': 'PrestaShop\LinkList\Form\Type\LinkBlockType'
    - 'AdminLinkWidget'
