parameters:
  hello_world: "Hello world!"

services:
  prestashop.link_block.repository:
    class: PrestaShop\LinkList\Repository\LinkBlockRepository
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  # Grid data query builder
  prestashop.link_block.grid.query_builder:
    class: PrestaShop\LinkList\Core\Grid\Query\LinkBlockQueryBuilder
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  # Grid Data Factory
  prestashop.link_block.grid.data_factory:
    class: PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory
    arguments:
      $gridQueryBuilder: '@prestashop.link_block.grid.query_builder'

  # Link block grid Factory
  prestashop.link_block.grid.factory:
    autowire: true
    class: PrestaShop\LinkList\Core\Grid\LinkBlockGridFactory
    arguments:
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
      $dataFactory: '@prestashop.link_block.grid.data_factory'
      $filterFormFactory: '@prestashop.core.grid.filter.form_factory'

  # Link block form data provider
  prestashop.link_block.form_provider:
    class: PrestaShop\LinkList\Form\LinkBlockFormDataProvider

  prestashop.link_block.choice_provider.hook:
    class: PrestaShop\LinkList\Form\ChoiceProvider\HookChoiceProvider
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  prestashop.link_block.choice_provider.cms_category:
    class: PrestaShop\LinkList\Form\ChoiceProvider\CMSCategoryChoiceProvider
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $idLang: '@=service("prestashop.adapter.legacy.context").getLanguage().id'
      $idShop: '@=service("prestashop.adapter.shop.context").getContextShopID()'

  prestashop.link_block.choice_provider.cms_page:
    class: PrestaShop\LinkList\Form\ChoiceProvider\CMSPageChoiceProvider
    arguments:
      $cmsCategoryChoiceProvider: '@prestashop.link_block.choice_provider.cms_category'
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $idLang: '@=service("prestashop.adapter.legacy.context").getLanguage().id'
      $idShop: '@=service("prestashop.adapter.shop.context").getContextShopID()'

  prestashop.link_block.choice_provider.product_page:
    class: PrestaShop\LinkList\Form\ChoiceProvider\PageChoiceProvider
    arguments:
      $idLang: '@=service("prestashop.adapter.legacy.context").getLanguage().id'
      $pageNames:
        - 'prices-drop'
        - 'new-products'
        - 'best-sales'

  prestashop.link_block.choice_provider.static_page:
    class: PrestaShop\LinkList\Form\ChoiceProvider\PageChoiceProvider
    arguments:
      $idLang: '@=service("prestashop.adapter.legacy.context").getLanguage().id'
      $pageNames:
        - 'contact'
        - 'sitemap'
        - 'stores'
        - 'authentication'
        - 'my-account'

  prestashop.link_block.form_type:
    class: PrestaShop\LinkList\Form\Type\LinkBlockType
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      $hookChoiceProvider: '@prestashop.link_block.choice_provider.hook'
      $cmsPageChoiceProvider: '@prestashop.link_block.choice_provider.cms_page'
      $productPageChoiceProvider: '@prestashop.link_block.choice_provider.product_page'
      $staticPageChoiceProvider: '@prestashop.link_block.choice_provider.static_page'
    tags:
      - { name: form.type }

  # Link block form handler
  prestashop.link_block.form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\FormHandler'
    arguments:
      $formBuilder: '@=service("form.factory").createBuilder()'
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
      $formDataProvider: '@prestashop.link_block.form_provider'
      $formTypes:
        'link_block': 'PrestaShop\LinkList\Form\Type\LinkBlockType'
      $hookName: 'AdminLinkWidget'
